---
output:
  bookdown::html_document2:
    fig_caption: yes
editor_options:
  chunk_output_type: console
---

Echantillonnage aléatoire systématique {#SY-QUICK}
=========================================

Définitions
------------

En matière d'échantillonnage dans l'espace, le type d'échantillonnage appelé communément SY signifie un échantillonnage selon une grille régulière

Plusieurs points doivent caractériser cette grille

* La grille est placée au hasard sur la zone. En général, on tire au hasard le point origine de la grille dans une zone de la résolution de la grille.

* L'orientation ne doit pas être aléatoire

* Dans les SY, les unités d'échantillonnage sont très bien réparties au sein de la zone d'étude

  - Avantage : (1) estimations précises du total, de la moyenne, de la proportion,  et (2) il est possible de mettre en oeuvre des techniques de cartographie statistiques comme le krigeage.
  
  - Inconvénient : ils n'existe pas d'estimateur non biaisé de la variance d'échantillonnage 


fixer le nombre de points avec la résolution qui va dépndre du budget alloué au projet.

Exemple de grille
-----------------

```{r SYfig, fig.cap='Exemple de  grilles systématiques placées au hasard', out.width='110%',fig.asp=.75, fig.align='center',warning=FALSE}

MonEch <- sp::spsample( x = champSP , 
                    cellsize = 20 ,
                    type = "regular")

set.seed(2) # ne marche pas sinon
MonEch2 <- sp::spsample( x = champSP , 
                    cellsize = 20 ,
                    type = "regular")

tm_shape(champSP) + tm_raster() +
  tm_shape(shp = MonEch) + tm_symbols(col='black') +
  tm_shape(shp = MonEch2) + tm_symbols(col='green')+

tm_layout(legend.outside = TRUE)

```


théorie
------------

La moyenne peut être calculé avec l'estimateur SI
Exemple de mise en oeuvre
-------------------------

Voici un exemple de mise en oeuvre des calculs proposés au paragraphe précédent.

```{r}
terrainSY <- over(MonEch2, champSP)

#change class of object with sample data to SpatialPixelsDataFrame
gridded(MonEch2) <- TRUE

#compute number of strata from length of data file NB number of sampling units can be odd
numberofStrata <- floor(length(MonEch2) / 2)

#cluster the sampling units
myStrata <-
  stratify(MonEch2,
           nStrata = numberofStrata,
           equalArea = TRUE,
           nTry = 100)

myStrata.df <- as(myStrata, "data.frame")
data <- cbind(terrainSY, myStrata.df)

varh <- tapply(data$sim1,
               INDEX = data$stratumId,
               FUN = var)

nh <- tapply(data$sim1,
             INDEX = data$stratumId,
             FUN = length)

varmeanh<-varh/nh
wh<-nh/sum(nh)
semeanSTSI<-sqrt(sum(wh^2*varmeanh))

semeanSI <- sqrt(var(terrainSY$sim1)/length(MonEch2))

```

Ainsi, l'estimation de la variance d'échantillonnage dite naïve est $`r semeanSI`$. Cette valeur est supérieure à la valeur fournie par l'estimation avec le deuxième formule: $`r semeanSTSI`$
