--- 
title: "Cours Echantillonnage pour l'étude des propriétés du sol"
author: "Nicolas Saby, INRAe Infosol"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
github-repo: nsaby/cours-echantillonnage
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Notes de cours pour l'échantillonnage statistique dans l'espace"
---

Pourquoi ce cours {#WHY}
======================

Motivations
-----------

Les motivations pour ce cours sont les suivantes:

- Les cours de statistique classique ne s'attarde pas sur la discipline de l'échantillonnage
- La conception d'un protocole d'échantillonnage efficace et efficient est une première étape importante d'un projet de recherche
- Le plan d'échantillonnage détermine en grande partie la qualité du résultat final
- Les problèmes d'inférence statistique peuvent souvent être évités lorsque nla réflection commence avant que les données ne soient collectées


Définition
-----------

Le plan d'échantillonnage d'une enquête par sondage se réfère
* aux techniques utilisées pour sélectionner un échantillon probabiliste et
* aux méthodes utilisées pour obtenir des estimations des variables étudiées à partir de l'échantillon sélectionné.


Contenu
---------

- Proposer une vue d'ensemble des différents plans d'échantillonnage pour l'étude des milieux

- Connaissance des types de conception de base pour l'échantillonnage aléatoire : avantages et inconvénients...

- et des types de conception spatiale plus avancés

- Connaissance de la manière dont les informations annexes peuvent être utilisées dans le plan d'échantillonnage...

- ou dans l'inférence statistique.

- Connaissance de la manière dont les échantillons peuvent être sélectionnés dans `R`, et comment
les paramètres statistiques peuvent être estimés...

- et de la manière dont un plan d'échantillonnage peut être évalué ex ante avant la collecte des données




Ce cours est basé sur les travaux publié dans le livre [@de_gruijter_sampling_2006]. Les codes `R` sont également disponibles dans l'article de Brus et al [@brus_sampling_2019]


Objectifs 
---------

* Objectifs possibles de l'étude
 + Pour estimer des statistiques sommaires (moyenne, total, proportion) ou la fonction de distribution cumulative spatiale (SCDF) pour l'étude la zone (population) dans son ensemble
 + La même chose, mais maintenant pour plusieurs sous-domaines
 + Pour cartographier la variable d'intérêt
* Nous ne sommes pas intéressés par les changements au fil du temps
* La propriété d'intérêt ne change pas pendant la période d'enquête


L'Echantillonnage Probabiliste
----------------------------
Pour estimer les totaux ou les moyennes, **l'échantillonnage probabiliste** est le plus
approprié

- Par échantillonnage probabiliste, on entend un échantillonnage aléatoire tel que
- Toutes les unités de population ont une probabilité > 0 d'être sélectionnées
- Les probabilités d'inclusion sont connues
- NB Les probabilités d'inclusion ne doivent pas forcément être égales !
- Il existe de nombreuses façons de sélectionner les unités de population avec un échantillonnage probabiliste


Population discrète et population continue
---------------------------------------

Nous devons **bien** distinguer deux types de populations :

* Les populations discrètes : les objets naturels discrets correspondent naturellement aux unités d'échantillonnage. Le nombre total d'unités d'échantillonnage dans la  population ($N$) est finie

* Populations continues : 
les unités d'échantillonnage doivent être définies, par exemple carrés de 1 km × 1 km

Mais

* Nombre total d'unités d'échantillonnage dans une population continue peut être finie ou infinie

  + Fini : tous les carrés disjoints de 1 km multipliés par 1 km dans une zone  
  + Infini : points dans une zone


Libraries utilisées
---------

Nous avons besoin des librairies suivantes

```{r}
library(sp)
library(tmap)
library(rgdal)
library(ggplot2)

```
